name: Build-And-Publish

# Controls when the workflow will run
on:
  release:
    types: [released]
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
    # Build functions into psm1 file
    # Update psd1 file version and release details values
    # Copy psd1 and psm1 file to temp location
    # Validate psd1
    # Publish to PSGallery
    # Create zip file of psd1 and psm1
    # Attach to release
